import { Geist, Geist_Mono } from "next/font/google";
import { Big_Shoulders_Inline_Display } from "next/font/google";
import "./globals.css";
import Navbar from "./navbar.jsx";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const bigShoulders = Big_Shoulders_Inline_Display({
  subsets: ["latin"],
  weight: ["400", "700"],  // Select font weights
  variable: "--font-big-shoulders", // Define a CSS variable
});

export const metadata1 = {
  title: "Next.js App with Google Font",
  description: "Using Big Shoulders Inline font in Next.js",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${bigShoulders.variable} antialiased bg-white`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
